### ISSUE TITLE
In setup.cfg, should parameterized>=0.7.4 be in development dependencies or install_requires? in relation to PR #66

### ISSUE THREAD

**Issue by vidyap-xgboost** [jbesomi/texthero#82]
In [setup.cfg](https://github.com/jbesomi/texthero/blob/master/setup.cfg), should `parameterized>=0.7.4` be in **development** dependencies or **install_requires**?

As per the [documentation](https://github.com/jbesomi/texthero/blob/master/CONTRIBUTING.md), we don't have to run `pip install -e '.[dev]'` unless we're contributing to website documentation. But `./tests.sh` won't run unless I install `parameterized` library.

So shouldn't this be changed? Or am I wrong here?

This problem arises due to PR #66

**Comment by jbesomi** [comment]
Good point!

`parameterized` is used under `test_index`. Texthero's normal users should not need to have installed `parametrized`, and therefore it's okay to have it under `development`.

As you correctly pointed out, what's written in the CONTRIbuting.md is incorrect and we will need to update that and be more precise. Would you like to fix that?

Again, thanks! 👍

**Comment by vidyap-xgboost** [comment]
> Good point!
> 
> `parameterized` is used under `test_index`. Texthero's normal users should not need to have installed `parametrized`, and therefore it's okay to have it under `development`.
> 
> As you correctly pointed out, what's written in the CONTRIbuting.md is incorrect and we will need to update that and be more precise. Would you like to fix that?
> 
> Again, thanks!

Hello, I would like to do that. But I'm not sure what exactly should be edited in CONTRIBUTING.md?

**Comment by jbesomi** [comment]
Great, thank you!

There is a part that says something like:

> Install development dependencies (only required if you want to change the website doc)
>Development dependencies need to be installed to update the website documentation, i.e the content in texthero.org.

>In most cases, you do not need to update this. Changes from pull requests will be available to everyone only after a new release.

>pip install -e '.[dev]'


We need to update it and explain that:

1. All contributors need to install also the development dependencies (i.e remove "(only required if you want to change the website doc)")
1. Explain that some of the dev-dependencies will be used by any contributor to being able to execute locally the test (probably we need to link to the "testing" section)
1. Explain that some of the dev-dependencies are necessary if the contributor wants to update the website or run the website locally but that in most cases this kind of change should not be sent as a PR as this would instantaneously change the website. Imagine for instance someone adds a new function as a PR, it should not also update the documentation. This will be done later when a new version will be released. Otherwise, there will be a function under the APIs yet not present in the installable pip version.

Hope it's a bit more clear, thank you in advance! :)
